<?php
/**
 * Created by PhpStorm.
 * User: F1677943
 * Date: 2017/11/21
 * Time: 下午 03:53
 */

namespace app\modules\system\models\show;


use app\modules\system\models\RMenuBtnDt;

class RMenuBtnDtShow extends RMenuBtnDt
{
    public function fields()
    {
        $fields = parent::fields();
        $fields['btn_name'] = function () {
            return $this->btnPk['btn_name'];
        };
        $fields['btn_yn'] = function () {
            return $this->btnPk['btn_yn'];
        };
        return $fields; // TODO: Change the autogenerated stub
    }
}