<?php
/**
 * Created by PhpStorm.
 * User: F3858997
 * Date: 2017/2/22
 * Time: 下午 05:26
 */
namespace app\modules\sale\models\show;
use app\modules\sale\models\SaleCostList;

class SaleCostListShow extends SaleCostList{

    public function fields()
    {
        $fields =  parent::fields(); // TODO: Change the autogenerated stub
        $fields['createBy'] = function () {
            return [
                "name"=>$this->creatorStaff['staff_name'],
                "code"=>$this->creatorStaff['staff_code'],
//                'mail'=>$this->creatorStaff['staff_email'],
//                'mobile'=>$this->creatorStaff['staff_mobile'],
//                'organization_code'=>$this->creatorStaff['organization_code'],
            ];
        };
        $fields['updateBy'] = function () {
            return [
                "name"=>$this->updateStaff['staff_name'],
                "code"=>$this->updateStaff['staff_code'],
//                'mail'=>$this->updateStaff['staff_email'],
//                'mobile'=>$this->updateStaff['staff_mobile'],
//                'organization_code'=>$this->updateStaff['organization_code'],
            ];
        };


        return $fields;
    }
}