<?php
/**
 * Created by PhpStorm.
 * User: F3860965
 * Date: 2017/8/30
 * Time: 上午 08:27
 */

namespace app\modules\crm\models\show;


use app\modules\crm\models\CrmC;

class CrmCShow extends CrmC
{
public function fields()
{
    $fields= parent::fields(); // TODO: Change the autogenerated stub
    return $fields;
}
}