<?php
/**
 * Created by PhpStorm.
 * User: F3860965
 * Date: 2017/8/22
 * Time: 上午 08:53
 */

namespace app\modules\warehouse\models\show;


use app\modules\common\models\BsDistrict;
use app\modules\warehouse\models\OrdLgst;

class OrdLgstShow extends OrdLgst
{
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        //物流订单ID
        $fields['ord_lg_id'] = function () {
            return $this->ord_lg_id;
        };
        //出库单ID
        $fields['o_whpkid'] = function () {
            return $this->o_whpkid;
        };
        //物流订单编号
        $fields['lg_no'] = function () {
            return $this->lg_no;
        };
        //是否富金机配送
        $fields['YN_FJJ'] = function () {
            if ($this->YN_FJJ == '0') {
                return "否";
            } else {
                return "是";
            }
        };
        //运输模式
        $fields['TRANSMODE'] = function () {
            if($this->TRANSMODE=='5')
            {
                return "陆运";
            }
            else{
                return "快递";
            }

        };
        //取件时间
        $fields['Fetch_date'] = function () {
            return $this->Fetch_date;
        };
        //客户签收时间
        $fields['rcpt_date'] = function () {
            return $this->rcpt_date;
        };
        //申请人
        $fields['crter']=function (){
            return $this->hrStaff['staff_name'];
        };
        //申请时间
        $fields['crt_date']=function (){
            return $this->crt_date;
        };
        //仓库代码
        $fields['wh_code']=function (){
          return $this->bsWh['wh_code'];
        };
        //仓库名称
        $fields['wh_name']=function (){
            return $this->bsWh['wh_name'];
        };
        //出貨聯系人
        $fields['shp_cntct'] = function () {
            return $this->shp_cntct;
        };
        //出貨聯系人電話
        $fields['shp_tel'] = function () {
            return $this->shp_tel;
        };
        //出货备注
        $fields['shp_marks'] = function () {
            return $this->shp_marks;
        };
        //收货联系人
        $fields['rcv_cntct'] = function () {
            return $this->rcv_cntct;
        };
        //收货联系人电话
        $fields['rcv_tel'] = function () {
            return $this->rcv_tel;
        };
        //收货备注
        $fields['rcv_marks'] = function () {
            return $this->rcv_marks;
        };
        //物流订单审核状态
        $fields['check_status'] = function () {
            if ($this->check_status == '2') {
                return "开立";
            } elseif ($this->check_status == '0') {
                return "审核中";
            } elseif ($this->check_status == '1') {
                return "审核完成";
            } elseif($this->check_status == '3') {
                return "发送物流";
            }
            else{
                return "驳回";
            }
        };
        //物流进度
        $fields['log_copy']=function (){
            if($this->check_status == '1'||$this->check_status == '3')
            {
                return "物流进度";
            }
        };
        //来源单据类型
        $fields['sr_type'] = function () {
            return "客户订单";

        };
        //预计出货时间
        $fields['lgst_date']=function (){
            return $this->lgst_date;
        };
        //贸易性质
        $fields['trade_act']=function (){
            return $this->trade_act;
        };
        //运输类型
        $fields['trade_type']=function (){
            if($this->trade_type=="201")
            {
                return "标准快递";
            }
            elseif ($this->trade_type=="202")
            {
                return "经济快递";
            }
            elseif ($this->trade_type=="203")
            {
                return "优速快递";
            }
            elseif ($this->trade_type=="301")
            {
                return "普通陆运";
            }
            else{
                return "定日达陆运";
            }
        };
        //是否無帳
        $fields['YN_Fee']=function (){
            if($this->YN_Fee=='0'){
                return  "否";
            }
            else{
                return "是";
            }
        };
        //是否保税
        $fields['YN_ins']=function (){
            if($this->YN_ins=='0')
            {
                return "否";
            }
            else{
                return "是";
            }
        };
        //费用代码
        $fields['cost_no']=function (){
            return $this->cost_no;
        };
        //進出口類型
        $fields['ie_type']=function (){
            if($this->ie_type=='0')
            {
                return "出口";
            }
            else
            {
                return "进口";
            }
        };
        //车种
        $fields['kd_car']=function (){
            return $this->kd_car;
        };
        //备注
        $fields['marks']=function (){
            return $this->marks;
        };
        //备注
        $fields['marks']=function (){
            return $this->marks;
        };
       //目的地
        $fields['destination']=function (){
//          $addr[]=$this->ordAddr['delivery_addr'];
           $address_id = $this->ordInfo['receipt_areaid'];//最后一阶的地址代码
            $addr[] = "";
            while ($address_id > 0) {
                $addr_info = BsDistrict::findOne($address_id);
                $address_id = $addr_info->district_pid;
                $addr[] = $addr_info->district_name;
            }
            return implode(" ", array_reverse($addr));
        };
        //起始地
        $fields['start_address']=function (){
                $address_id = $this->bsWh['district_id'];//最后一阶的地址代码
                $addr[] = "";
                while ($address_id > 0) {
                    $addr_info = BsDistrict::findOne($address_id);
                    $address_id = $addr_info->district_pid;
                    $addr[] = $addr_info->district_name;
                }
                return implode(" ", array_reverse($addr));
        };
        return $fields;
    }
}