<?php
/**
 * Created by PhpStorm.
 * User: F3860965
 * Date: 2017/8/23
 * Time: 下午 03:04
 */

namespace app\modules\warehouse\models\show;


use app\modules\warehouse\models\OrdLgstDt;

class OrdLgstDtShow extends OrdLgstDt
{
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        //物流订单ID
        $fields['ord_lg_id'] = function () {
            return $this->ord_lg_id;
        };
        //出库单ID
        $fields['ord_shp_PKID'] = function () {
            return $this->ordLg['ord_shp_PKID'];
        };
        //物流订单编号
        $fields['lg_no'] = function () {
            return $this->ordLg['lg_no'];
        };
        //是否富金机配送
        $fields['YN_FJJ'] = function () {
            if ($this->ordLg['YN_FJJ'] == '0') {
                return "否";
            } else {
                return "是";
            }
        };
        //运输模式
        $fields['TRANSMODE'] = function () {
            return $this->ordLg['TRANSMODE'];
        };
        //取件时间
        $fields['Fetch_date'] = function () {
            return $this->ordLg['Fetch_date'];
        };
        //客户签收时间
        $fields['rcpt_date'] = function () {
            return $this->ordLg['rcpt_date'];
        };
        //申请人
        $fields['crter']=function (){
            return $this->ordLg['crter'];
        };
        //申请时间
        $fields['crt_date']=function (){
            return $this->ordLg['crt_date'];
        };
        //出貨聯系人
        $fields['shp_cntct'] = function () {
            return $this->ordLg['shp_cntct'];
        };
        //出貨聯系人電話
        $fields['shp_tel'] = function () {
            return $this->ordLg['shp_tel'];
        };
        //出货备注
        $fields['shp_marks'] = function () {
            return $this->ordLg['shp_marks'];
        };
        //收货联系人
        $fields['rcv_cntct'] = function () {
            return $this->ordLg['rcv_cntct'];
        };
        //收货联系人电话
        $fields['rcv_tel'] = function () {
            return $this->ordLg['rcv_tel'];
        };
        //收货备注
        $fields['rcv_marks'] = function () {
            return $this->ordLg['rcv_marks'];
        };
        //物流订单状态
        $fields['check_status'] = function () {
            if ($this->ordLg['check_status'] == '0') {
                return "开立";
            } elseif ($this->ordLg['check_status'] == '1') {
                return "审核中";
            } elseif ($this->ordLg['check_status'] == '2') {
                return "审核完成";
            } else {
                return "发送物流";
            }
        };
        //物流进度
        $fields['log_copy']=function (){
            if($this->ordLg['check_status'] == '2'||$this->ordLg['check_status'] == '3')
            {
                return "物流进度";
            }
        };
        //来源单据类型
        $fields['sr_type'] = function () {
            return $this->ordLg['sr_type'];
        };
        //预计出货时间
        $fields['lgst_date']=function (){
            return $this->ordLg['lgst_date'];
        };
        //贸易性质
        $fields['trade_act']=function (){
            return $this->ordLg['trade_act'];
        };
        //运输类型
        $fields['trade_type']=function (){
            return $this->ordLg['trade_type'];
        };
        //是否無帳
        $fields['YN_Fee']=function (){
            if($this->ordLg['YN_Fee']=='0'){
                return  "否";
            }
            else{
                return "是";
            }
        };
        //是否保税
        $fields['YN_ins']=function (){
            if($this->ordLg['YN_ins']=='0')
            {
                return "否";
            }
            else{
                return "是";
            }
        };
        //费用代码
        $fields['cost_no']=function (){
            return $this->ordLg['cost_no'];
        };
        //進出口類型
        $fields['ie_type']=function (){
            if($this->ordLg['ie_type']=='0')
            {
                return "出口";
            }
            else
            {
                return "进口";
            }
        };
        //车种
        $fields['kd_car']=function (){
            return $this->ordLg['kd_car'];
        };
        //备注
        $fields['marks']=function (){
            return $this->ordLg['marks'];
        };
        //目的地
        $fields['destination']=function (){
            return $this->saleOrderh['delivery_addr'];
        };
        //起始地
        $fields['start_address']=function (){
            return "DD";
        };
        return $fields;
    }
}